// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  GED
// DateTime: 26/05/2020 15:07:18
// UserName: przem
// Input file <Parser.y - 26/05/2020 12:07:18>

// options: lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace MiniCompiler
{
public enum Tokens {error=2,EOF=3,Program=4,OpenBrace=5,CloseBrace=6,
    Return=7,Colon=8,Endl=9,Eof=10,Error=11,Write=12,
    Assign=13,Plus=14,Minus=15,Multiplies=16,Divides=17,OpenPar=18,
    ClosePar=19,IntA=20,DoubleA=21,BoolA=22,Id=23,IntVal=24,
    DoubleVal=25,True=26,False=27};

public struct ValueType
#line 8 "Parser.y"
{
    public string  val;
    public char    type;
}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[28];
  private static State[] states = new State[28];
  private static string[] nonTerms = new string[] {
      "content", "newline", "blokInstr", "declare", "exp", "term", "factor", 
      "start", "$accept", "end", };

  static Parser() {
    states[0] = new State(new int[]{4,3,9,8,10,9,2,10},new int[]{-8,1,-2,6});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{9,8,5,18,2,26},new int[]{-3,4,-2,12});
    states[4] = new State(new int[]{4,3,9,8,10,9,2,10},new int[]{-8,5,-2,6});
    states[5] = new State(-2);
    states[6] = new State(new int[]{4,3,9,8,10,9,2,10},new int[]{-8,7,-2,6});
    states[7] = new State(-3);
    states[8] = new State(-15);
    states[9] = new State(-4);
    states[10] = new State(new int[]{10,11});
    states[11] = new State(-5);
    states[12] = new State(new int[]{5,13});
    states[13] = new State(new int[]{9,8,6,-12},new int[]{-1,14,-2,16});
    states[14] = new State(new int[]{6,15});
    states[15] = new State(-6);
    states[16] = new State(new int[]{9,8,6,-12},new int[]{-1,17,-2,16});
    states[17] = new State(-11);
    states[18] = new State(new int[]{2,23,9,8,5,18,6,-12},new int[]{-1,19,-3,21,-2,25});
    states[19] = new State(new int[]{6,20});
    states[20] = new State(-7);
    states[21] = new State(new int[]{6,22});
    states[22] = new State(-8);
    states[23] = new State(new int[]{10,24});
    states[24] = new State(-9);
    states[25] = new State(new int[]{5,13,9,8,6,-12},new int[]{-1,17,-2,16});
    states[26] = new State(new int[]{10,27});
    states[27] = new State(-10);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-9, new int[]{-8,3});
    rules[2] = new Rule(-8, new int[]{4,-3,-8});
    rules[3] = new Rule(-8, new int[]{-2,-8});
    rules[4] = new Rule(-8, new int[]{10});
    rules[5] = new Rule(-8, new int[]{2,10});
    rules[6] = new Rule(-3, new int[]{-2,5,-1,6});
    rules[7] = new Rule(-3, new int[]{5,-1,6});
    rules[8] = new Rule(-3, new int[]{5,-3,6});
    rules[9] = new Rule(-3, new int[]{5,2,10});
    rules[10] = new Rule(-3, new int[]{2,10});
    rules[11] = new Rule(-1, new int[]{-2,-1});
    rules[12] = new Rule(-1, new int[]{});
    rules[13] = new Rule(-4, new int[]{20,23,8});
    rules[14] = new Rule(-4, new int[]{21,23,8});
    rules[15] = new Rule(-2, new int[]{9});
    rules[16] = new Rule(-10, new int[]{8});
    rules[17] = new Rule(-10, new int[]{10});
    rules[18] = new Rule(-5, new int[]{-5,14,-6});
    rules[19] = new Rule(-5, new int[]{-5,15,-6});
    rules[20] = new Rule(-5, new int[]{-6});
    rules[21] = new Rule(-6, new int[]{-6,16,-7});
    rules[22] = new Rule(-6, new int[]{-6,17,-7});
    rules[23] = new Rule(-6, new int[]{-7});
    rules[24] = new Rule(-7, new int[]{18,-5,19});
    rules[25] = new Rule(-7, new int[]{24});
    rules[26] = new Rule(-7, new int[]{25});
    rules[27] = new Rule(-7, new int[]{23});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 4: // start -> Eof
#line 27 "Parser.y"
                {
                   Compiler.EmitCode("// linia {0,3} :  "+ Compiler.sourceLines[lineNum - 1], lineNum);
                   Compiler.EmitCode("ldstr \"\\nEnd of execution\\n\"");
                   Compiler.EmitCode("call void [mscorlib]System.Console::WriteLine(string)");
                   Compiler.EmitCode("");
                   YYAccept();
                }
#line default
        break;
      case 5: // start -> error, Eof
#line 35 "Parser.y"
                {
                    Console.WriteLine("  line {0,3}: 'program' statement required.", lineNum);
                    ++Compiler.errors;
                    yyerrok();
                    YYAbort();
                }
#line default
        break;
      case 7: // blokInstr -> OpenBrace, content, CloseBrace
#line 44 "Parser.y"
                {
                }
#line default
        break;
      case 9: // blokInstr -> OpenBrace, error, Eof
#line 48 "Parser.y"
                {
                    Console.WriteLine("  line {0,3}: No brace matching.", lineNum);
                    ++Compiler.errors;
                    yyerrok();
                    YYAbort();
                }
#line default
        break;
      case 10: // blokInstr -> error, Eof
#line 55 "Parser.y"
                {
                    Console.WriteLine("  line {0,3}: Braces expected.", lineNum);
                    ++Compiler.errors;
                    yyerrok();
                    YYAbort();
                }
#line default
        break;
      case 15: // newline -> Endl
#line 70 "Parser.y"
                     { ++lineNum; }
#line default
        break;
      case 17: // end -> Eof
#line 75 "Parser.y"
                {
                    Console.WriteLine("  line {0,3}:  syntax error - unexpected symbol Eof", lineNum);
                    ++Compiler.errors;
                    yyerrok();
                    YYAbort();
                }
#line default
        break;
      case 18: // exp -> exp, Plus, term
#line 88 "Parser.y"
                   { CurrentSemanticValue.type = BinaryOpGenCode(Tokens.Plus, ValueStack[ValueStack.Depth-3].type, ValueStack[ValueStack.Depth-1].type); }
#line default
        break;
      case 19: // exp -> exp, Minus, term
#line 90 "Parser.y"
                   { CurrentSemanticValue.type = BinaryOpGenCode(Tokens.Minus, ValueStack[ValueStack.Depth-3].type, ValueStack[ValueStack.Depth-1].type); }
#line default
        break;
      case 20: // exp -> term
#line 92 "Parser.y"
                   { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 21: // term -> term, Multiplies, factor
#line 96 "Parser.y"
                   { CurrentSemanticValue.type = BinaryOpGenCode(Tokens.Multiplies, ValueStack[ValueStack.Depth-3].type, ValueStack[ValueStack.Depth-1].type); }
#line default
        break;
      case 22: // term -> term, Divides, factor
#line 98 "Parser.y"
                   { CurrentSemanticValue.type = BinaryOpGenCode(Tokens.Divides, ValueStack[ValueStack.Depth-3].type, ValueStack[ValueStack.Depth-1].type); }
#line default
        break;
      case 23: // term -> factor
#line 100 "Parser.y"
                   { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 24: // factor -> OpenPar, exp, ClosePar
#line 104 "Parser.y"
                   { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-2].type; }
#line default
        break;
      case 25: // factor -> IntVal
#line 106 "Parser.y"
                   {
                   Compiler.EmitCode("ldc.i4 {0}",int.Parse(ValueStack[ValueStack.Depth-1].val));
                   CurrentSemanticValue.type = 'i'; 
                   }
#line default
        break;
      case 26: // factor -> DoubleVal
#line 111 "Parser.y"
                   {
                   double d = double.Parse(ValueStack[ValueStack.Depth-1].val,System.Globalization.CultureInfo.InvariantCulture) ;
                   Compiler.EmitCode(string.Format(System.Globalization.CultureInfo.InvariantCulture,"ldc.r8 {0}",d));
                   CurrentSemanticValue.type = 'r'; 
                   }
#line default
        break;
      case 27: // factor -> Id
#line 117 "Parser.y"
                {
                    Compiler.EmitCode("ldloc _{0}{1}", ValueStack[ValueStack.Depth-1].val[0]=='@'?'i':'r', ValueStack[ValueStack.Depth-1].val[1]);
                    CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].val[0]=='@'?'i':'r';
                }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 124 "Parser.y"

/* HELPER FUNCTIONS ------------------------------------------------------------------------------------------------*/

int lineNum = 1;

public Parser(Scanner scanner) : base(scanner) { }

private char BinaryOpGenCode(Tokens t, char type1, char type2)
{
    char type = ( type1=='i' && type2=='i' ) ? 'i' : 'r' ;
    if ( type1!=type )
        {
        Compiler.EmitCode("stloc temp");
        Compiler.EmitCode("conv.r8");
        Compiler.EmitCode("ldloc temp");
        }
    if ( type2!=type )
        Compiler.EmitCode("conv.r8");
    switch ( t )
        {
        case Tokens.Plus:
            Compiler.EmitCode("add");
            break;
        case Tokens.Minus:
            Compiler.EmitCode("sub");
            break;
        case Tokens.Multiplies:
            Compiler.EmitCode("mul");
            break;
        case Tokens.Divides:
            Compiler.EmitCode("div");
            break;
        default:
            Console.WriteLine($"  line {lineNum,3}:  internal gencode error");
            ++Compiler.errors;
            break;
        }
    return type;
}
#line default
}
}
